# Generated by Django 4.0.5 on 2022-06-10 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_carro', models.CharField(max_length=30)),
                ('marcas_de_carros', models.CharField(choices=[('Citroen', 'Citroen'), ('Chevrolet', 'Chevrolet'), ('Ferrari', 'Ferrari'), ('Fiat', 'Fiat'), ('Ford', 'Ford'), ('Hyundai', 'Hyundai'), ('Jeep', 'Jeep'), ('Mercedes Benz', 'Mercedes Benz'), ('Peugeot', 'Peugeot'), ('Outros', 'Outros'), ('Renault', 'Renault'), ('Toyota', 'Toyota'), ('Volkswagen', 'Volkswagen')], max_length=30)),
                ('valor_do_carro', models.CharField(choices=[('Entre R$ 0 e R$ 40.000,00', 'Entre R$ 0 e R$ 40.000,00'), ('Entre R$ 40.000,01 e R$ 80.000,00', 'Entre R$ 40.000,01 e R$ 80.000,00'), ('Entre R$ 80.000,01 e R$ 120.000,00', 'Entre R$ 80.000,01 e R$120.000,00'), ('Não sabe informar', 'Não sabe informar')], max_length=50)),
                ('modelos_de_carros', models.CharField(choices=[('Hatch', 'Hatch'), ('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Outros', 'Outros')], max_length=30)),
                ('fotos_de_carros', models.ImageField(blank=True, null=True, upload_to='clients_photos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
                'ordering': ['nome_do_carro'],
            },
        ),
    ]
