# Generated by Django 4.0.5 on 2022-06-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0005_alter_carros_fotos_de_carros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carros',
            name='fotos_de_carros',
            field=models.ImageField(blank=True, null=True, upload_to='clients_photos', verbose_name='Fotos'),
        ),
        migrations.AlterField(
            model_name='carros',
            name='modelos_de_carros',
            field=models.CharField(choices=[('1.0', '1.0'), ('1.4', '1.4'), ('1.6', '1.6'), ('1.8', '1.8'), ('2.0', '2.0'), ('4.0', '4.0')], max_length=30, verbose_name='Motor'),
        ),
    ]
