# Generated by Django 4.0.5 on 2022-06-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0008_alter_carros_fotos_de_carros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carros',
            name='nome_do_carro',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
