# Generated by Django 4.0.5 on 2022-07-01 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0009_alter_carros_nome_do_carro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carros',
            name='nome_do_carro',
            field=models.CharField(max_length=30),
        ),
    ]
