# Generated by Django 4.0.5 on 2022-07-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0010_alter_carros_nome_do_carro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carros',
            name='marcas_de_carros',
            field=models.CharField(choices=[('Citroen', 'Citroen'), ('Chevrolet', 'Chevrolet'), ('Ferrari', 'Ferrari'), ('Fiat', 'Fiat'), ('Ford', 'Ford'), ('Hyundai', 'Hyundai'), ('Jeep', 'Jeep'), ('Mercedes Benz', 'Mercedes Benz'), ('Peugeot', 'Peugeot'), ('Outros', 'Outros'), ('Renault', 'Renault'), ('Toyota', 'Toyota'), ('Volkswagen', 'Volkswagen')], max_length=30, verbose_name='Fabricante'),
        ),
        migrations.AlterField(
            model_name='carros',
            name='nome_do_carro',
            field=models.CharField(max_length=30, verbose_name='Modelo de Carro'),
        ),
    ]
