# Generated by Django 4.0.5 on 2022-07-01 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0011_alter_carros_marcas_de_carros_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carros',
            name='nome_do_carro',
            field=models.CharField(max_length=30, verbose_name='Modelo do Carro'),
        ),
    ]
