# Generated by Django 4.0.5 on 2022-07-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0012_alter_carros_nome_do_carro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carros',
            name='marcas_de_carros',
            field=models.CharField(choices=[('Citroen', 'Citroen'), ('Chevrolet', 'Chevrolet'), ('Ferrari', 'Ferrari'), ('Fiat', 'Fiat'), ('Ford', 'Ford'), ('Hyundai', 'Hyundai'), ('Jeep', 'Jeep'), ('Mercedes Benz', 'Mercedes Benz'), ('Peugeot', 'Peugeot'), ('Outros', 'Outros'), ('Renault', 'Renault'), ('Toyota', 'Toyota'), ('Volkswagen', 'Volkswagen')], max_length=30, verbose_name='Fabricante:'),
        ),
        migrations.AlterField(
            model_name='carros',
            name='modelos_de_carros',
            field=models.CharField(choices=[('1.0', '1.0'), ('1.4', '1.4'), ('1.6', '1.6'), ('1.8', '1.8'), ('2.0', '2.0'), ('4.0', '4.0')], max_length=30, verbose_name='Motor:'),
        ),
        migrations.AlterField(
            model_name='carros',
            name='nome_do_carro',
            field=models.CharField(max_length=30, verbose_name='Modelo do Carro:'),
        ),
        migrations.AlterField(
            model_name='carros',
            name='valor_do_carro',
            field=models.CharField(choices=[('Entre R$ 0 e R$ 40.000,00', 'Entre R$ 0 e R$ 40.000,00'), ('Entre R$ 40.000,01 e R$ 80.000,00', 'Entre R$ 40.000,01 e R$ 80.000,00'), ('Entre R$ 80.000,01 e R$ 120.000,00', 'Entre R$ 80.000,01 e R$120.000,00'), ('Entre R$ 120.000,01 e R$ 240.000,00', 'Entre R$ 120.000,01 e R$ 240.000,00'), ('Entre R$ 240.000,01 e R$ 480.000,00', 'Entre R$ 240.000,01 e R$ 480.000,00'), ('Entre R$ 480.000,01 e R$ 960.000,00', 'Entre R$ 480.000,01 e R$ 960.000,00'), ('Não sabe informar', 'Não sabe informar')], max_length=50, verbose_name='Valor do Carro:'),
        ),
    ]
