# Generated by Django 4.0.5 on 2022-07-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0014_alter_carros_modelos_de_carros'),
    ]

    operations = [
        migrations.AddField(
            model_name='carros',
            name='motorizacao',
            field=models.TextField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default=1, max_length=5, verbose_name='Turbo:'),
            preserve_default=False,
        ),
    ]
