# Generated by Django 4.0.5 on 2022-07-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0016_alter_carros_motorizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carros',
            name='modelos_de_carros',
            field=models.CharField(choices=[('1.0', '1.0'), ('1.4', '1.4'), ('1.6', '1.6'), ('1.8', '1.8'), ('2.0', '2.0'), ('2.4', '2.4'), ('2.8', '2.8'), ('3.2', '3.2'), ('4.0', '4.0')], default='1.0', max_length=30, verbose_name='Motor:'),
        ),
    ]
