# Generated by Django 4.0.5 on 2022-07-07 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0023_alter_carros_motorizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carros',
            name='motorizacao',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', help_text='O carro tem motorização turbo?', max_length=10, verbose_name='Turbo:'),
        ),
    ]
