# Generated by Django 4.0.5 on 2022-08-05 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0025_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='clients_photos', verbose_name='Foto:'),
        ),
    ]
